// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisFaculdadeApi.Data;

namespace SisFaculdadeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221004064322_change-tabela-curso-aluno")]
    partial class changetabelacursoaluno
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SisFaculdadeApi.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = new DateTime(2000, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Caio Henrique"
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernando Fernandes"
                        },
                        new
                        {
                            Id = 3,
                            DataNascimento = new DateTime(2000, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Lídia Alteres"
                        },
                        new
                        {
                            Id = 4,
                            DataNascimento = new DateTime(2000, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Afrígia Ramone"
                        },
                        new
                        {
                            Id = 5,
                            DataNascimento = new DateTime(2000, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Simone Teles"
                        },
                        new
                        {
                            Id = 6,
                            DataNascimento = new DateTime(1998, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Sérgio Ricardo"
                        },
                        new
                        {
                            Id = 7,
                            DataNascimento = new DateTime(2000, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Cleide Silva"
                        },
                        new
                        {
                            Id = 8,
                            DataNascimento = new DateTime(2000, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "José Arthur"
                        },
                        new
                        {
                            Id = 9,
                            DataNascimento = new DateTime(2000, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Davi Riquelme"
                        },
                        new
                        {
                            Id = 10,
                            DataNascimento = new DateTime(2000, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Willy Sebára"
                        },
                        new
                        {
                            Id = 11,
                            DataNascimento = new DateTime(2002, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jaime Leal"
                        },
                        new
                        {
                            Id = 12,
                            DataNascimento = new DateTime(2000, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pedro Oliveira"
                        },
                        new
                        {
                            Id = 13,
                            DataNascimento = new DateTime(2000, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Denise Dutra"
                        },
                        new
                        {
                            Id = 14,
                            DataNascimento = new DateTime(2000, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Igor Godói"
                        },
                        new
                        {
                            Id = 15,
                            DataNascimento = new DateTime(2003, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Denis Oliveira"
                        },
                        new
                        {
                            Id = 16,
                            DataNascimento = new DateTime(2000, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Billy Regis"
                        },
                        new
                        {
                            Id = 17,
                            DataNascimento = new DateTime(2000, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maria Antônia"
                        },
                        new
                        {
                            Id = 18,
                            DataNascimento = new DateTime(2000, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Marcos José"
                        },
                        new
                        {
                            Id = 19,
                            DataNascimento = new DateTime(2004, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Itálo Jonas"
                        },
                        new
                        {
                            Id = 20,
                            DataNascimento = new DateTime(2000, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Flora Antonina"
                        },
                        new
                        {
                            Id = 21,
                            DataNascimento = new DateTime(2001, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gaspar Oliveira"
                        },
                        new
                        {
                            Id = 22,
                            DataNascimento = new DateTime(2000, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Camily Netunes"
                        },
                        new
                        {
                            Id = 23,
                            DataNascimento = new DateTime(1999, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jessica Heloísa"
                        },
                        new
                        {
                            Id = 24,
                            DataNascimento = new DateTime(2000, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Cinthia Rodrigues"
                        },
                        new
                        {
                            Id = 25,
                            DataNascimento = new DateTime(1998, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Regina Mendes"
                        },
                        new
                        {
                            Id = 26,
                            DataNascimento = new DateTime(2000, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pedro de Sousa"
                        },
                        new
                        {
                            Id = 27,
                            DataNascimento = new DateTime(2000, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Quirino Santos"
                        },
                        new
                        {
                            Id = 28,
                            DataNascimento = new DateTime(2000, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Alirio Alares"
                        },
                        new
                        {
                            Id = 29,
                            DataNascimento = new DateTime(2000, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Eduardo Santi"
                        },
                        new
                        {
                            Id = 30,
                            DataNascimento = new DateTime(2000, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maurício Barbosa"
                        },
                        new
                        {
                            Id = 31,
                            DataNascimento = new DateTime(1997, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Elvira Silva"
                        },
                        new
                        {
                            Id = 32,
                            DataNascimento = new DateTime(1996, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ana Eloísa"
                        },
                        new
                        {
                            Id = 33,
                            DataNascimento = new DateTime(1995, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Miriam Pedrosa"
                        },
                        new
                        {
                            Id = 34,
                            DataNascimento = new DateTime(1994, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Carlos Torres"
                        },
                        new
                        {
                            Id = 35,
                            DataNascimento = new DateTime(1993, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Silvana Abigail"
                        });
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            AlunoId = 9,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 10,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 11,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 12,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 13,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 14,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 15,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 16,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 17,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 18,
                            CursoId = 2
                        },
                        new
                        {
                            AlunoId = 19,
                            CursoId = 3
                        },
                        new
                        {
                            AlunoId = 20,
                            CursoId = 3
                        },
                        new
                        {
                            AlunoId = 21,
                            CursoId = 3
                        },
                        new
                        {
                            AlunoId = 22,
                            CursoId = 3
                        },
                        new
                        {
                            AlunoId = 23,
                            CursoId = 3
                        },
                        new
                        {
                            AlunoId = 24,
                            CursoId = 3
                        },
                        new
                        {
                            AlunoId = 25,
                            CursoId = 4
                        },
                        new
                        {
                            AlunoId = 26,
                            CursoId = 4
                        },
                        new
                        {
                            AlunoId = 27,
                            CursoId = 4
                        },
                        new
                        {
                            AlunoId = 28,
                            CursoId = 4
                        },
                        new
                        {
                            AlunoId = 29,
                            CursoId = 4
                        },
                        new
                        {
                            AlunoId = 30,
                            CursoId = 4
                        },
                        new
                        {
                            AlunoId = 31,
                            CursoId = 5
                        },
                        new
                        {
                            AlunoId = 32,
                            CursoId = 5
                        },
                        new
                        {
                            AlunoId = 33,
                            CursoId = 5
                        },
                        new
                        {
                            AlunoId = 34,
                            CursoId = 5
                        },
                        new
                        {
                            AlunoId = 35,
                            CursoId = 5
                        });
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ciências da Computação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Marketing e Publicidade"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciências da Comunicação"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Serviço Social"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Direito"
                        });
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.CursoDisciplina", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.HasKey("CursoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("CursosDisciplinas");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            DisciplinaId = 1
                        },
                        new
                        {
                            CursoId = 1,
                            DisciplinaId = 2
                        },
                        new
                        {
                            CursoId = 1,
                            DisciplinaId = 3
                        },
                        new
                        {
                            CursoId = 1,
                            DisciplinaId = 4
                        },
                        new
                        {
                            CursoId = 1,
                            DisciplinaId = 5
                        },
                        new
                        {
                            CursoId = 1,
                            DisciplinaId = 6
                        },
                        new
                        {
                            CursoId = 1,
                            DisciplinaId = 10
                        },
                        new
                        {
                            CursoId = 1,
                            DisciplinaId = 12
                        },
                        new
                        {
                            CursoId = 2,
                            DisciplinaId = 10
                        },
                        new
                        {
                            CursoId = 2,
                            DisciplinaId = 12
                        },
                        new
                        {
                            CursoId = 2,
                            DisciplinaId = 13
                        },
                        new
                        {
                            CursoId = 3,
                            DisciplinaId = 10
                        },
                        new
                        {
                            CursoId = 3,
                            DisciplinaId = 12
                        },
                        new
                        {
                            CursoId = 3,
                            DisciplinaId = 13
                        },
                        new
                        {
                            CursoId = 4,
                            DisciplinaId = 10
                        },
                        new
                        {
                            CursoId = 4,
                            DisciplinaId = 12
                        },
                        new
                        {
                            CursoId = 4,
                            DisciplinaId = 11
                        },
                        new
                        {
                            CursoId = 4,
                            DisciplinaId = 13
                        },
                        new
                        {
                            CursoId = 4,
                            DisciplinaId = 16
                        },
                        new
                        {
                            CursoId = 5,
                            DisciplinaId = 10
                        },
                        new
                        {
                            CursoId = 5,
                            DisciplinaId = 12
                        },
                        new
                        {
                            CursoId = 5,
                            DisciplinaId = 11
                        },
                        new
                        {
                            CursoId = 5,
                            DisciplinaId = 13
                        },
                        new
                        {
                            CursoId = 5,
                            DisciplinaId = 14
                        },
                        new
                        {
                            CursoId = 5,
                            DisciplinaId = 15
                        });
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Arquitetura de Computadores",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Banco de Dados I",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Banco de Dados II",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Administração e Serviços de Rede",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Estrutura de Dados",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Redes de Computadores",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Sociologia",
                            ProfessorId = 7
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Direito e Legislação Social",
                            ProfessorId = 7
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Política Social",
                            ProfessorId = 6
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Estado, Sociedade e Movimentos Sociais",
                            ProfessorId = 7
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Administração e Planejamento em Serviço Social",
                            ProfessorId = 7
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Projeto de Conclusão de Curso",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Direito Administrativo",
                            ProfessorId = 8
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Direito Penal",
                            ProfessorId = 8
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Direito Constitucional",
                            ProfessorId = 8
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Estágio supervisionado",
                            ProfessorId = 8
                        });
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.DisciplinaAluno", b =>
                {
                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<double?>("Nota")
                        .HasColumnType("float");

                    b.HasKey("DisciplinaId", "AlunoId", "CursoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("CursoId");

                    b.ToTable("DisciplinasAlunos");

                    b.HasData(
                        new
                        {
                            DisciplinaId = 1,
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 1,
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 1,
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 1,
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 1,
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 1,
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 1,
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 1,
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 2,
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 2,
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 2,
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 2,
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 2,
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 2,
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 2,
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 2,
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 3,
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 3,
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 3,
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 3,
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 3,
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 3,
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 3,
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 3,
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 4,
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 4,
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 4,
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 4,
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 4,
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 4,
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 4,
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 4,
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 5,
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 5,
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 5,
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 5,
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 5,
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 5,
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 5,
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 5,
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 6,
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 6,
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 6,
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 6,
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 6,
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 6,
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 6,
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 6,
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 1,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 2,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 3,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 4,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 5,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 6,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 7,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 8,
                            CursoId = 1
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 9,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 10,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 11,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 12,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 13,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 14,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 15,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 16,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 17,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 18,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 9,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 10,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 11,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 12,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 13,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 14,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 15,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 16,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 17,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 18,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 9,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 10,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 11,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 12,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 13,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 14,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 15,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 16,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 17,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 18,
                            CursoId = 2
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 19,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 20,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 21,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 22,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 23,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 24,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 19,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 20,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 21,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 22,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 23,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 24,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 19,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 20,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 21,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 22,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 23,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 24,
                            CursoId = 3
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 25,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 26,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 27,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 28,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 29,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 30,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 25,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 26,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 27,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 28,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 29,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 30,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 25,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 26,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 27,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 28,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 29,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 30,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 25,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 26,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 27,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 28,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 29,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 30,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 16,
                            AlunoId = 25,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 16,
                            AlunoId = 26,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 16,
                            AlunoId = 27,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 16,
                            AlunoId = 28,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 16,
                            AlunoId = 29,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 16,
                            AlunoId = 30,
                            CursoId = 4
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 31,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 32,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 33,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 34,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 10,
                            AlunoId = 35,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 31,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 32,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 33,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 34,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 11,
                            AlunoId = 35,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 31,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 32,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 33,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 34,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 12,
                            AlunoId = 35,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 31,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 32,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 33,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 34,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 13,
                            AlunoId = 35,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 14,
                            AlunoId = 31,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 14,
                            AlunoId = 32,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 14,
                            AlunoId = 33,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 14,
                            AlunoId = 34,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 14,
                            AlunoId = 35,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 15,
                            AlunoId = 31,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 15,
                            AlunoId = 32,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 15,
                            AlunoId = 33,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 15,
                            AlunoId = 34,
                            CursoId = 5
                        },
                        new
                        {
                            DisciplinaId = 15,
                            AlunoId = 35,
                            CursoId = 5
                        });
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("Salario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = new DateTime(1980, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ângelo Mota",
                            Salario = 1323.0
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = new DateTime(1985, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Flávia Andrade",
                            Salario = 1323.0
                        },
                        new
                        {
                            Id = 3,
                            DataNascimento = new DateTime(1978, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Hugo Rodrigues",
                            Salario = 1323.0
                        },
                        new
                        {
                            Id = 4,
                            DataNascimento = new DateTime(1968, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Patrício Vilella",
                            Salario = 1323.0
                        },
                        new
                        {
                            Id = 5,
                            DataNascimento = new DateTime(1991, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rafael Oliveira",
                            Salario = 1323.0
                        },
                        new
                        {
                            Id = 6,
                            DataNascimento = new DateTime(1984, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Danilo Martins",
                            Salario = 1323.0
                        },
                        new
                        {
                            Id = 7,
                            DataNascimento = new DateTime(1990, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ana Silva",
                            Salario = 1323.0
                        },
                        new
                        {
                            Id = 8,
                            DataNascimento = new DateTime(1963, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rui Fernando",
                            Salario = 1323.0
                        });
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.AlunoCurso", b =>
                {
                    b.HasOne("SisFaculdadeApi.Models.Aluno", null)
                        .WithMany("AlunosCursos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisFaculdadeApi.Models.Curso", null)
                        .WithMany("AlunosCursos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.CursoDisciplina", b =>
                {
                    b.HasOne("SisFaculdadeApi.Models.Curso", null)
                        .WithMany("CursosDisciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisFaculdadeApi.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.Disciplina", b =>
                {
                    b.HasOne("SisFaculdadeApi.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.DisciplinaAluno", b =>
                {
                    b.HasOne("SisFaculdadeApi.Models.Aluno", "Aluno")
                        .WithMany("DisciplinasAlunos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisFaculdadeApi.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisFaculdadeApi.Models.Disciplina", "Disciplina")
                        .WithMany("DisciplinasAlunos")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.Aluno", b =>
                {
                    b.Navigation("AlunosCursos");

                    b.Navigation("DisciplinasAlunos");
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.Curso", b =>
                {
                    b.Navigation("AlunosCursos");

                    b.Navigation("CursosDisciplinas");
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.Disciplina", b =>
                {
                    b.Navigation("DisciplinasAlunos");
                });

            modelBuilder.Entity("SisFaculdadeApi.Models.Professor", b =>
                {
                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
